image: node:22

definitions:
  caches:
    pnpm: .pnpm-store

pipelines:
  branches:
    release/mainnet:
      - step:
          name: Build & Deploy to Cloudflare Pages
          deployment: production
          caches:
            - node
            - pnpm
          script:
            - corepack enable
            - corepack prepare pnpm@9 --activate
            - pnpm config set store-dir .pnpm-store
            - pnpm install --frozen-lockfile
            - pnpm run build
            - pnpm run deploy:production
